name: Create SBOM
description: "Syft based action to create SBOM (Software Bill of Materials) for a specific docker image"

inputs:
  image_name:
    required: true
    default: ""
    description: "Name of the image for which the SBOM should be created. This should contain repository and image tag."
  output_format:
    required: false
    default: "text"
    description: "The output format of the SBOM. Lookup syft's output formats for more detail"

runs:
  using: "composite"
  steps:
    - name: Install syft
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v1.0.1

    - name: Create SBOM
      shell: bash
      run: |
        set -ex
        syft ghcr.io/${{ inputs.image_name }} --from registry -o ${{ inputs.output_format }} > SBOM

    - name: Archive SBOM
      uses: actions/upload-artifact@v4
      with:
        name: SBOM
        path: SBOM
